### ISSUE TITLE
Isomorphic blank node comparison

### ISSUE THREAD

**Issue by wschella** [rubensworks/rdf-test-suite.js#38]
Comparing by term equality forces the implementation to use the same blank node naming scheme as the test suite.

**Comment by rubensworks** [comment]
In what situation does this occur? I assume for tests that return bindings?

For quad results we already do isomorphic testing, so for bindings we may want to do something similar (which won't be a trivial thing to implement).

**Comment by wschella** [comment]
This occurs in the spec test for bnode01 and bnode01

<https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/functions/bnode01.rq>
<https://github.com/w3c/rdf-tests/blob/gh-pages/sparql11/data-sparql11/functions/bnode01.srx>

**Comment by wschella** [comment]
Nice! Does this fix the spec errors in comunica?

**Comment by rubensworks** [comment]
Yes, it fixed quite a few of them.

The `BNODE(str)` test does not pass yet though. It looks like this one fails because of an incorrect implementation, but I'll have to look into it a bit more.

**Comment by wschella** [comment]
That's nice to hear :) An incorrect implementation seems likely, reading the spec definition again, I'm quite certain i misinterpreted it during the original implementation,
