### ISSUE TITLE
Crash when running without summary

### ISSUE THREAD

**Issue by FlorianFV** [rubensworks/rdf-test-suite.js#58]
When running the test suite and let it print the errors and differences, following error occurs:

https://hastebin.com/akusogiqek.sql

on line: https://github.com/rubensworks/rdf-test-suite.js/blob/master/lib/TestSuiteRunner.ts#L153

**Comment by rubensworks** [comment]
What is the exact command you execute to trigger this error?

**Comment by FlorianFV** [comment]
`yarn run spec-base -e`

**Comment by rubensworks** [comment]
For reference: https://github.com/comunica/comunica/blob/master/packages/actor-init-sparql/package.json#L189
