### ISSUE TITLE
Loaded test files are occasionally empty

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-test-suite.js#81]
Note quite sure the exact conditions that caused this to occur but my best guess would be an unstable internet connection when running the spec test.

When this happens; the spec file that gets loaded and cached is empty, even though it should not be (in particular this happened to me with https://w3c.github.io/rdf-star/tests/turtle/syntax#nt-ttl-star-bad-2).

Clearing the cache and re-running the spec tests resolved this issue for me.

**Comment by rubensworks** [comment]
I think this is the same problem as #64.
