### ISSUE TITLE
Handling a single test with multiple types

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-test-suite.js#87]
The following test suite from the latest N3 spec contains some tests that are *both* negative turtle tests and positive n3 tests; I'm wondering you think is the best behavior to handle these tests @rubensworks. My view is that there should be a separate test entry created *for each type* so that only one handler is needed per entry still; and then we should add a filter option to allow for whitelisting or blacklisting test types when running the spec test.

https://w3c.github.io/N3/tests/TurtleTests/manifest.ttl

**Comment by rubensworks** [comment]
Ah, that's annoying.

> My view is that there should be a separate test entry created for each type so that only one handler is needed per entry still

That would be my preference as well.

But if the test manifest can not be changed, we could also change rdf-test-suite so that it can instantiate tests multiple times based on their (multiple) types.

**Comment by jeswr** [comment]
This is resolved by #89.
