### ISSUE TITLE
Support `mf:assumedTestBase`

### ISSUE THREAD

**Issue by jeswr** [rubensworks/rdf-test-suite.js#94]
See https://github.com/w3c/rdf-tests/pull/116 for expected usage.

~I'm looking into this now.~

**EDIT** I am personally deprioritising work on this as N3.js is back to having spec tests passing after upgrading to the latest spec references and version of rdf-test-suite.

**Comment by rubensworks** [comment]
We should also update the links in the README to the new manifest locations before closing this issue.

**Comment by rubensworks** [comment]
Now that the README has been updated, I guess this one can be closed.
